name: vitality_vault
description: A new Flutter project.
environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: 6.1.5
  google_fonts: 6.2.1
  lottie: 3.3.1
  cloud_firestore: 5.6.9
  flutter_signin_button: 2.0.0
  firebase_storage: ^12.4.7
  js: 0.7.2
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  google_sign_in: ^6.3.0
  animated_text_kit: ^4.2.2
  file_picker: ^5.5.0
  dotted_border: ^2.1.0
  flutter_dropzone: ^4.0.0
  path: ^1.8.2
  uuid: ^4.5.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/animations/heart_intro.json
    - assets/images/google_logo.png

