// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANYqT8gY2Py4rx9ud0BVGK7xuHxmQl8rE',
    appId: '1:54118745711:web:e14db2d129eeed9665ef9a',
    messagingSenderId: '54118745711',
    projectId: 'avid-influence-462814-a4',
    authDomain: 'avid-influence-462814-a4.firebaseapp.com',
    storageBucket: 'avid-influence-462814-a4.firebasestorage.app',
    measurementId: 'G-KM9K62SB9D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjbkm6MKUHSr9cF4szGQX6AVIUd2sDN2Y',
    appId: '1:54118745711:android:a3268d47009401bd65ef9a',
    messagingSenderId: '54118745711',
    projectId: 'avid-influence-462814-a4',
    storageBucket: 'avid-influence-462814-a4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQPA3J5MEqOaAsRqyCeHHZYaebJ4mq_Og',
    appId: '1:54118745711:ios:4c1a6ff0ac3ae7bb65ef9a',
    messagingSenderId: '54118745711',
    projectId: 'avid-influence-462814-a4',
    storageBucket: 'avid-influence-462814-a4.firebasestorage.app',
    iosClientId: '54118745711-414j18hcd4bmjqsjpd2je7e1scmm2mdd.apps.googleusercontent.com',
    iosBundleId: 'com.example.vitalityVaultFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQPA3J5MEqOaAsRqyCeHHZYaebJ4mq_Og',
    appId: '1:54118745711:ios:4c1a6ff0ac3ae7bb65ef9a',
    messagingSenderId: '54118745711',
    projectId: 'avid-influence-462814-a4',
    storageBucket: 'avid-influence-462814-a4.firebasestorage.app',
    iosClientId: '54118745711-414j18hcd4bmjqsjpd2je7e1scmm2mdd.apps.googleusercontent.com',
    iosBundleId: 'com.example.vitalityVaultFrontend',
  );
}
